# Check the baseline data

This is for
1. Checking if the `_conf.py` actually is correct.
2. See the available baseline data. In this case, the available baseline configurations for the comparison.

In [8]:
from _conf import (
    INPUT_SAMPLE_ARCHIVE,
    INSTANCE_ARCHIVE,
)
from _utils import get_instance, parse_sample, parse_solution_overview

In [9]:
samples = parse_solution_overview(INPUT_SAMPLE_ARCHIVE)
samples

Found the data folders: {'2024-02-23_21-52-36/', '2024-02-23_21-52-29/', '2024-02-20_15-34-55/', '2024-02-20_15-35-55/', '2024-02-23_21-52-42/', '2024-02-23_21-52-24/'}
Deleting YASA entries
Deleting YASA entries
Deleting YASA entries
Deleting YASA entries
Deleting YASA entries
Deleting YASA entries

,ModelID,AlgorithmID,SystemIteration,AlgorithmIteration,InTime,Success,Time,SampleSize,Instance,#Variables,#Clauses,Algorithm,Settings,Path,Time(s)
0,1,0,1,1,True,True,62188,96,aaed2000,1298,3036,FIDE-ICPL,t2,2024-02-23_21-52-36/1_1_0_1_sample.csv,62.188
1,1,1,1,1,False,True,900003,0,aaed2000,1298,3036,FIDE-Chvatal,t2,None,900.003
2,1,2,1,1,True,True,48432,161,aaed2000,1298,3036,Incling,t2,2024-02-23_21-52-36/1_1_2_1_sample.csv,48.432
3,1,3,1,1,True,True,4939,102,aaed2000,1298,3036,FIDE-YASA,t2_m1_null,2024-02-23_21-52-36/1_1_3_1_sample.csv,4.939
4,1,4,1,1,True,True,10284,94,aaed2000,1298,3036,FIDE-YASA,t2_m3_null,2024-02-23_21-52-36/1_1_4_1_sample.csv,10.284
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2580,9,6,5,1,True,True,22795,67,atlas_mips32_4kc,1229,2875,FIDE-YASA,t2_m10_null,2024-02-23_21-52-24/9_5_6_1_sample.csv,22.795
2581,9,7,5,1,False,True,900001,0,atlas_mips32_4kc,1229,2875,ACTS-IPOG-FT,t2,None,900.001
2582,9,8,5,1,False,True,900009,0,atlas_mips32_4kc,1229,2875,ACTS-IPOG-CSP,t2,None,900.009
2583,9,9,5,1,False,True,900008,0,atlas_mips32_4kc,1229,2875,ACTS-IPOF-FT,t2,None,900.008
2584,9,10,5,1,False,True,900008,0,atlas_mips32_4kc,1229,2875,ACTS-IPOF-CSP,t2,None,900.008

In [10]:
samples[["Algorithm", "Settings"]].drop_duplicates()

        Algorithm     Settings
0       FIDE-ICPL           t2
1    FIDE-Chvatal           t2
2         Incling           t2
3       FIDE-YASA   t2_m1_null
4       FIDE-YASA   t2_m3_null
5       FIDE-YASA   t2_m5_null
6       FIDE-YASA  t2_m10_null
7    ACTS-IPOG-FT           t2
8   ACTS-IPOG-CSP           t2
9    ACTS-IPOF-FT           t2
10  ACTS-IPOF-CSP           t2

In [11]:
# YASA m=1 samples

yasa_m1 = samples[
    (samples["Algorithm"] == "FIDE-YASA") & (samples["Settings"] == "t2_m1_null")
].dropna()
yasa_m1

,ModelID,AlgorithmID,SystemIteration,AlgorithmIteration,InTime,Success,Time,SampleSize,Instance,#Variables,#Clauses,Algorithm,Settings,Path,Time(s)
3,1,3,1,1,True,True,4939,102,aaed2000,1298,3036,FIDE-YASA,t2_m1_null,2024-02-23_21-52-36/1_1_3_1_sample.csv,4.939
14,1,3,2,1,True,True,4767,104,aaed2000,1298,3036,FIDE-YASA,t2_m1_null,2024-02-23_21-52-36/1_2_3_1_sample.csv,4.767
25,1,3,3,1,True,True,4989,105,aaed2000,1298,3036,FIDE-YASA,t2_m1_null,2024-02-23_21-52-36/1_3_3_1_sample.csv,4.989
36,1,3,4,1,True,True,5061,108,aaed2000,1298,3036,FIDE-YASA,t2_m1_null,2024-02-23_21-52-36/1_4_3_1_sample.csv,5.061
47,1,3,5,1,True,True,4772,100,aaed2000,1298,3036,FIDE-YASA,t2_m1_null,2024-02-23_21-52-36/1_5_3_1_sample.csv,4.772
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2533,9,3,1,1,True,True,4348,80,atlas_mips32_4kc,1229,2875,FIDE-YASA,t2_m1_null,2024-02-23_21-52-24/9_1_3_1_sample.csv,4.348
2544,9,3,2,1,True,True,4177,74,atlas_mips32_4kc,1229,2875,FIDE-YASA,t2_m1_null,2024-02-23_21-52-24/9_2_3_1_sample.csv,4.177
2555,9,3,3,1,True,True,4098,75,atlas_mips32_4kc,1229,2875,FIDE-YASA,t2_m1_null,2024-02-23_21-52-24/9_3_3_1_sample.csv,4.098
2566,9,3,4,1,True,True,4235,76,atlas_mips32_4kc,1229,2875,FIDE-YASA,t2_m1_null,2024-02-23_21-52-24/9_4_3_1_sample.csv,4.235
2577,9,3,5,1,True,True,4262,76,atlas_mips32_4kc,1229,2875,FIDE-YASA,t2_m1_null,2024-02-23_21-52-24/9_5_3_1_sample.csv,4.262

In [12]:
parse_sample(INPUT_SAMPLE_ARCHIVE, yasa_m1.iloc[0]["Path"])

[{'CYGIMP_POSIX_MQUEUE_VALIDATE_DESCRIPTOR': True,
  'CYGBLD_GLOBAL_WARNFLAGS': True,
  'CYGNUM_KERNEL_THREADS_STACK_CHECK_DATA_SIZE': True,
  'CYGSEM_MEMALLOC_ALLOCATOR_VARIABLE_COALESCE': True,
  'CYGSEM_LIBM_THREAD_SAFE_GAMMA_FUNCTIONS': True,
  'CYGPKG_LIBC_TIME_CFLAGS_REMOVE': False,
  'CYGPKG_IO_ETH_DRIVERS_SIMULATE_LINE_CUT': True,
  'CYGNUM_IO_ETH_DRIVERS_NUM_PKT': False,
  'TMP_MAX': False,
  'CYGINT_IO_SERIAL_TEST_SKIP_115200': True,
  'CYGPKG_NET_TFTPD_THREAD_PRIORITY': True,
  'CYGPKG_LIBC_I18N_OPTIONS': False,
  'CYGSEM_AAED2000_LCD_PORTRAIT_MODE': True,
  'CYGNUM_IO_FLASH_TEST_LENGTH': True,
  'CYGINT_ISO_MQUEUE': True,
  'CYGVAR_KERNEL_COUNTERS_CLOCK': True,
  'CYGNUM_KERNEL_SCHED_PRIORITIES': True,
  'CYGPKG_NET_FAST_THREAD_TICKLE_DEVS': True,
  'CYGINT_ISO_STRING_LOCALE_FUNCS': True,
  'CYGFUN_KERNEL_API_C': True,
  'CYGHWR_HAL_ARM_CPU_FAMILY': True,
  'CYGOPT_FS_JFFS2_COMPRESS_CMODE': True,
  'CYGSEM_LIBC_I18N_PER_THREAD_MB': False,
  'CYGPKG_POSIX_CLOCKS': True,
  'CYGIMP_KERNEL_COUNTERS_SINGLE_LIST': False,
  'CYGINT_ISO_TERMIOS': True,
  'CYGSEM_KERNEL_SYNCH_MUTEX_PRIORITY_INVERSION_PROTOCOL_INHERIT': False,
  'CYGDBG_INFRA_DEBUG_TRACE_BUFFER_PRINT': True,
  'CYGNUM_UITRON_STACK_SIZE': True,
  'CYGPKG_POSIX_TIMERS': True,
  'CYGPKG_ISOINFRA_OPTIONS': True,
  'CYGPKG_UITRON_MEMPOOLFIXED_CREATE_DELETE': True,
  'CYGNUM_LIBC_ATEXIT_HANDLERS': False,
  'CYGNUM_HAL_DEBUG_GDB_PROTOCOL_TIMEOUT': True,
  'CYGNUM_HTTPD_SERVER_DELAY': True,
  'CYGPKG_DEVS_FLASH_AMD_AM29XXXXX': True,
  'CYGIMP_LIBC_STDLIB_INLINE_DIV': False,
  'CYGDBG_KERNEL_INSTRUMENT_SCHED': True,
  'CYGHWR_DEVS_FLASH_AMD_AM29LV320D': True,
  'CYGPKG_COMPRESS_ZLIB_CFLAGS_ADD': True,
  'CYGHWR_NET_DRIVER_ETH1_ADDRS_SERVER': False,
  'CYGPKG_IO_SERIAL_OPTIONS': True,
  'CYGPKG_IO_SERIAL_TESTS': True,
  'CYGPKG_LIBC_STRING_OPTIONS': False,
  'CYGDBG_HAL_DEBUG_GDB_BREAK_SUPPORT': False,
  'CYGPKG_INFRA_LDFLAGS_REMOVE': True,
  'CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD': True,
  'CYGIMP_DEVS_ETH_CL_CS8900A_DATABUS_8BIT': False,
  'CYGPKG_KERNEL': True,
  'CYGPKG_IO_WALLCLOCK_TESTS': True,
  'CYGNUM_UITRON_SEMAS': True,
  'CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD': True,
  'CYGPKG_UITRON_CYCLICS': True,
  'CYGPKG_REDBOOT_ARM_LINUX_EXEC': False,
  'CYGPKG_UITRON_VERSION_PRNO': True,
  'CYGHWR_IO_FLASH_BLOCK_LOCKING': True,
  'CYGDAT_UITRON_TASK_EXTERNS': True,
  'CYGNUM_HAL_ARM_AAED2000_CLOCK_PREDIV': True,
  'CYG_POSIX_UTSNAME_NODENAME_LENGTH': True,
  'CYGPKG_IO_FLASH_CFLAGS_ADD': True,
  'CYGNUM_HAL_DEBUG_GDB_PROTOCOL_RETRIES': True,
  'CYGNUM_KERNEL_SCHED_TIMESLICE_TICKS': True,
  'CYGIMP_LIBC_RAND_KNUTH1': False,
  'CYGDAT_DEVS_TOUCH_AAED2000_NAME': True,
  'CYGNUM_IO_FILEIO_MAX_INODE_CACHE_DEAD': True,
  'CYGPKG_LIBC_TIME_TESTS': False,
  'CYGPKG_IO_DISK': True,
  'CYGPKG_INFRA_DEBUG': True,
  'CYGPKG_COMPRESS_ZLIB_TESTS': True,
  'CYGINT_ISO_DNS': True,
  'CYGBLD_BUILD_REDBOOT_BIN': False,
  'CYGHWR_NET_DRIVER_ETH1_MANUAL': False,
  'CYGPKG_UITRON_FLAGS_CREATE_DELETE': True,
  'CYGPKG_LIBC_STARTUP_OPTIONS': False,
  'CYGPKG_NET_FAST_THREAD_PRIORITY': True,
  'CYGPKG_NET_TFTPD_THREAD_STACK_SIZE': True,
  'CYGBLD_ARCH_LDFLAGS': False,
  'CYGPKG_IO_ETH_DRIVERS_OPTIONS': True,
  'CYGBLD_ISO_FSTYPES_HEADER': True,
  'CYGIMP_IDLE_THREAD_YIELD': True,
  'CYGINT_ISO_STDIO_FORMATTED_IO': True,
  'CYGPKG_INFRA_STARTUP': True,
  'CYGNUM_IO_FLASH_BLOCK_ABSOLUTE_START_1': False,
  'CYGPKG_POSIX_PTHREAD_VALUES': True,
  'CYGNUM_ISO_MQUEUE_OPEN_MAX': True,
  'CYGPKG_NET_FREEBSD_INET': True,
  'CYGFUN_LIBC_STDIO_LONGLONG': False,
  'CYGBLD_ISO_DLFCN_HEADER': True,
  'CYGPKG_KERNEL_API': True,
  'CYGPKG_NS_DNS_OPTIONS': True,
  'CYGNUM_NET_THREAD_STACKSIZE': True,
  'CYGNUM_PPP_CHAT_ABORTS_MAX': True,
  'CYGOPT_NET_DHCP_OPTION_DHCP_CLIENTID_MAC': True,
  'CYGIMP_KERNEL_INTERRUPTS_CHAIN': True,
  'CYGPKG_NET_STACK_INET': True,
  'CYGINT_ISO_ENVIRON': True,
  'CYGPKG_IO_FLASH_TESTS': True,
  'CYGBLD_BUILD_COMMON_GDB_STUBS': False,
  'CYGPKG_IO_SERIAL_TTY_TTY0': True,
  'CYGIMP_KERNEL_COUNTERS_SORT_LIST': True,
  'CYGPKG_INFRA_OPTIONS': True,
  'CYGPKG_POSIX_SEMAPHORES': True,
  'CYGPKG_ISO_LIMITS': True,
  'CYGNUM_IO_FLASH_BLOCK_ABSOLUTE_LENGTH_1': False,
  'CYGPKG_ISO_SCHED': True,
  'CYGINT_ISO_BSEARCH': True,
  'CYGPKG_NET_FORCE_SERIAL_CONSOLE': True,
  'CYGDAT_UITRON_TASK_INITIALIZERS': True,
  'CYGBLD_HAL_LINKER_GROUPED_LIBS_DEFAULT': True,
  'CYGNUM_IO_FLASH_BLOCK_OFFSET_2': False,
  'CYGOPT_IO_SERIAL_SUPPORT_LINE_STATUS': True,
  'CYGPKG_ISO_POSIX_TYPES': True,
  'CYGPKG_IO_SERIAL_TTY_TTY1': True,
  'CYGDBG_KERNEL_INSTRUMENT_INTR': True,
  'CYGPKG_LIBC_SETJMP_CFLAGS_ADD': False,
  'CYGOPT_HAL_ARM_PRESERVE_SVC_SPSR': True,
  'CYGINT_WATCHDOG_HW_IMPLEMENTATIONS': True,
  'CYGPKG_DEVS_ETH_ARM_AAED2000': True,
  'CYGNUM_IO_FLASH_BLOCK_OFFSET_1': True,
  'CYGINT_ISO_STDLIB_STRCONV_FLOAT': True,
  'CYGFUN_LIBC_STDIO_ungetc': False,
  'CYGPKG_LIBC_STRING_TESTS': False,
  'CYGSEM_LIBM_COMPAT_IEEE_ONLY_alt': True,
  'CYGOPT_FS_JFFS2_COMPRESS_RTIME': True,
  'CYGINT_ISO_EXIT': True,
  'CYGPKG_FS_RAM': True,
  'CYGDAT_VNC_SERVER_MOUSE_NAME': True,
  'CYGPKG_MEMALLOC_ALLOCATOR_DLMALLOC': True,
  'CYGINT_FS_RAM_ALLOC': True,
  'CYGSEM_LIBM_THREAD_SAFE_COMPAT_MODE': False,
  'CYGPKG_NET_STACK': True,
  'CYGNUM_NET_FAST_THREAD_STACKSIZE': True,
  'CYGINT_HAL_DEBUG_GDB_STUBS': True,
  'CYGBLD_ISO_STDIO_DIRECT_IO_HEADER': True,
  'CYGIMP_KERNEL_INTERRUPTS_DSRS_LIST_alt': True,
  'CYGNUM_VNC_SERVER_PIXEL_RGB332': True,
  'CYGPKG_IO_SERIAL_TTY': True,
  'CYGNUM_UITRON_VER_PRNO_0': True,
  'CYGPKG_HAL_ARM_ARM9_AAED2000_CFLAGS_ADD': True,
  'CYGSEM_MEMALLOC_ALLOCATOR_SEPMETA_THREADAWARE': True,
  'CYGOPT_FS_JFFS2_COMPRESS_RUBIN': True,
  'CYGSEM_HAL_ENABLE_DCACHE_ON_STARTUP': True,
  'CYGFUN_POSIX_MQUEUE_NOTIFY': True,
  'CYGSEM_HAL_USE_ROM_MONITOR': True,
  'CYGNUM_HAL_ARM_AAED2000_CLOCK_MAINDIV2': True,
  'CYGDBG_INFRA_DEBUG_LOOP_INVARIANTS': True,
  'CYGPKG_POWER_CFLAGS_REMOVE': True,
  'CYGSEM_MEMALLOC_ALLOCATOR_FIXED_THREADAWARE': True,
  'CYGOPT_IO_SERIAL_FLOW_CONTROL_HW': True,
  'CYGPKG_DEVS_DISK_TESTING': True,
  'CYGSEM_DEVS_ETH_ARM_AAED2000_ETH0_SET_ESA': True,
  'CYGINT_LIBC_STARTUP_CONTEXT': False,
  'CYGSEM_LIBC_STDIO_SETVBUF_MALLOC': False,
  'CYGNUM_HTTPD_THREAD_COUNT': True,
  'CYGDBG_KERNEL_INSTRUMENT_THREAD': True,
  'CYGHWR_DEVS_FLASH_AMD_AM29PL160': True,
  'CYGHWR_NET_DRIVER_ETH1_ADDRS_BROADCAST': False,
  'CYGPKG_MEMALLOC_MALLOC_ALLOCATORS': True,
  'CYGPKG_IO_WALLCLOCK_CFLAGS_REMOVE': True,
  'CYGINT_IO_SERIAL_TEST_SKIP_STOP_2': True,
  'CYGPKG_LIBC_STARTUP_CFLAGS_REMOVE': False,
  'CYGIMP_KERNEL_INTERRUPTS_DSRS': True,
  'CYGNUM_VNC_SERVER_PORT': True,
  'CYGPKG_KERNEL_OPTIONS': True,
  'CYGBLD_ISO_TZSET_HEADER': True,
  'CYGBLD_ISO_OPEN_MAX_HEADER': True,
  'CYGINT_HAL_PLF_IF_INIT': True,
  'CYGPKG_NET_DHCP_THREAD_STACK_SIZE': True,
  'CYGPKG_LIBC': False,
  'CYGPKG_LIBC_STARTUP_CONTEXT': False,
  'CYGBLD_ISO_STRING_LOCALE_FUNCS_HEADER': True,
  'CYGPKG_REDBOOT_HAL_OPTIONS': False,
  'CYGINT_ISO_STRERROR': True,
  'CYGSEM_UITRON_BAD_PARAMS_RETURN_ERRORS': True,
  'CYGHWR_IO_FLASH_DEVICE_NEEDS_CACHE_HANDLED': True,
  'CYGPKG_HAL_ARM_ARM9_ARM926EJ': False,
  'CYGPKG_IO_SERIAL_HALDIAG': True,
  'CYGINT_DEVS_ETH_CL_CS8900A_REQUIRED': True,
  'CYGSEM_MEMALLOC_MALLOC_ZERO_RETURNS_NULL': True,
  'CYGINT_LIBC_I18N_MB_REQUIRED': False,
  'CYGINT_ISO_STDIO_CHAR_IO': True,
  'CYGPKG_MEMALLOC_ALLOCATOR_SEPMETA': True,
  'CYGHWR_NET_DRIVER_ETH1_IPV6_PREFIX': False,
  'CYGPKG_DEVS_TOUCH_AAED2000_CFLAGS': True,
  'CYGPKG_ERROR_STRERROR': True,
  'CYGPRI_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_CONFIGURABLE': True,
  'CYGPKG_NET_TESTS_USE_RT_TEST_HARNESS': True,
  'CYGPKG_PPP_PAP': True,
  'CYGINT_ISO_POSIX_SLEEP': True,
  'CYGPKG_LIBM_COMPATIBILITY': True,
  'CYGDAT_NET_SNMPAGENT_SYS_CONTACT': True,
  'CYGFUN_LIBC_I18N_LOCALE_C_SJIS': False,
  'CYGPKG_POSIX_SCHED': True,
  'CYGSEM_KERNEL_SYNCH_MUTEX_PRIORITY_INVERSION_PROTOCOL_DEFAULT': False,
  'CYGPKG_SNMPLIB_FILESYSTEM_SUPPORT': True,
  'CYGNUM_KERNEL_MAX_SUSPEND_COUNT_ASSERT': True,
  'CYGPKG_HAL_TESTS': True,
  'CYGNUM_PPP_CHAT_ABORTS_SIZE': True,
  'CYGDAT_IO_SERIAL_TERMIOS_TERMIOS2_DEV': True,
  'CYGINT_COMPRESS_ZLIB_LOCAL_ALLOC': True,
  'CYGPKG_NS_DNS_CFLAGS_REMOVE': True,
  'CYGNUM_UITRON_ALARMS': True,
  'CYGFUN_KERNEL_ALL_THREADS_STACK_CHECKING': True,
  'CYGNUM_IO_FLASH_BLOCK_CFG_FIS_2': True,
  'CYGBLD_ISO_SSIZE_T_HEADER': True,
  'CYGPKG_POSIX': True,
  'CYGNUM_LIBC_BSEARCH_TRACE_LEVEL': False,
  'CYGPKG_ISO_STRING': True,
  'CYGSEM_KERNEL_SYNCH_MUTEX_PRIORITY_INVERSION_PROTOCOL_CEILING': False,
  'CYGDAT_LIBC_ARGUMENTS': False,
  'CYGNUM_UITRON_MEMPOOLFIXED_INITIALLY': True,
  'CYGNUM_VNC_SERVER_PIXEL_SELECTED': True,
  'CYGBLD_IO_SERIAL_TERMIOS_TERMIOS_TTY': True,
  'CYGPKG_NET_STACK_IPSEC': True,
  'CYGPKG_LIBC_STARTUP': False,
  'CYGPKG_POSIX_PTHREAD_FEATURES': True,
  'CYGSEM_NET_ROUTING': True,
  'CYGPKG_NS_DNS_BUILD': True,
  'CYGPKG_NS_DNS_TESTS_LUNN': True,
  'CYGNUM_LIBM_COMPAT_DEFAULT': False,
  'CYGPKG_POWER_TESTS': True,
  'CYGINT_HAL_TESTS_NO_CACHES': True,
  'CYGDBG_KERNEL_INSTRUMENT_CNTSEM': True,
  'CYGSEM_LIBC_STRING_PER_THREAD_STRTOK': False,
  'CYGPKG_HAL': True,
  'CYGSEM_LIBC_STDIO_SCANF_FLOATING_POINT': False,
  'CYGPKG_PPP_CHAP': True,
  'CYGINT_WALLCLOCK_HW_IMPLEMENTATIONS': True,
  'CYGNUM_FILEIO_MTAB_EXTRA': True,
  'CYGPKG_HAL_COMMON_CONTEXT': True,
  'CYGPKG_IO_FLASH_BLOCK_DEVICE_2': True,
  'L_tmpnam': False,
  'CYGPKG_ISO_CTYPE_H': True,
  'CYGIMP_LIBC_TIME_GMTIME_R_INLINE': False,
  'CYGIMP_UITRON_INLINE_FUNCS': True,
  'CYGIMP_KERNEL_INTERRUPTS_DSRS_LIST': False,
  'CYGPKG_LIBC_SETJMP_OPTIONS': False,
  'CYGSEM_HAL_ROM_MONITOR': True,
  'CYGPKG_IO_SERIAL_FLOW_CONTROL': True,
  'CYGINT_HAL_ARM_MEM_REAL_REGION_TOP': True,
  'CYGPKG_PPP_TESTS_ALL': True,
  'CYGDBG_USE_ASSERTS': True,
  'CYGPKG_UITRON_SEMAS': True,
  'CYGHWR_NET_DRIVER_ETH0_SETUP_OPTIONS': True,
  'CYGVAR_KERNEL_COUNTERS_CLOCK_LATENCY': True,
  'CYGNUM_NET_SNTP_UNICAST_MAXDHCP': False,
  'CYGPKG_NET_FTPCLIENT_TESTS': True,
  'CYGPKG_LIBM_CFLAGS_ADD': True,
  'CYGBLD_ISO_ERRNO_HEADER': True,
  'CYGBLD_ISO_SELECT_HEADER': True,
  'CYGPKG_MEMALLOC_OPTIONS': True,
  'CYGDBG_KERNEL_INSTRUMENT_FLAGS': True,
  'CYGPKG_LIBC_STDLIB_TESTS': False,
  'CYGSEM_LIBC_STDIO_PRINTF_FLOATING_POINT': False,
  'CYGSEM_IO_FLASH_READ_INDIRECT': False,
  'CYGINT_ISO_TZSET': True,
  'CYGINT_DEVS_FLASH_AMD_VARIANTS': True,
  'CYGHWR_HAL_ARM_BIGENDIAN': True,
  'CYGPKG_IO_FILEIO_INODE': True,
  'CYGINT_ISO_POSIX_CLOCKS': True,
  'CYGPKG_IO_SERIAL_DEVICES': True,
  'CYGOPT_FS_JFFS2_DEBUG': True,
  'CYGNUM_IO_FLASH_BLOCK_CFG_STATIC_2': False,
  'CYGBLD_ISO_POSIX_CLOCKS_HEADER': True,
  'CYGNUM_RAMFS_BLOCKS_INDIRECT1': True,
  'CYGINT_HAL_DEBUG_GDB_STUBS_BREAK': True,
  'CYGDAT_IO_FLASH_BLOCK_DEVICE_NAME_1': True,
  'CYGNUM_HAL_RTC_PERIOD': True,
  'CYGDAT_UITRON_SEMA_INITIALIZERS': True,
  'CYGNUM_UITRON_MBOXES': True,
  'CYGNUM_UITRON_FLAGS': True,
  'CYGPKG_HAL_COMMON': True,
  'CYGSEM_IO_FLASH_VERIFY_PROGRAM': True,
  'CYGPKG_SNMPLIB_OPTIONS': True,
  'CYGBLD_ISO_PTHREADTYPES_HEADER': True,
  'CYGHWR_DEVS_FLASH_AMD_AM29LV081B': True,
  'CYGBLD_ISO_C_CLOCK_FUNCS_HEADER': True,
  'CYGIMP_BLOCK_LIB_STATISTICS': True,
  'CYGBLD_ISO_MEMSET_HEADER': True,
  'CYGPKG_POSIX_PTHREAD_MUTEX': True,
  'CYGBLD_ISO_DNS_HEADER': True,
  'CYGPKG_HTTPD_TESTS': True,
  'CYGDBG_KERNEL_INSTRUMENT_MBOXT': True,
  'CYGPKG_SNMPAGENT_SYSTEM_MIB': True,
  'CYGTST_ROMFS_BUILD_TESTS': False,
  'CYGDBG_HAL_DIAG_TO_DEBUG_CHAN': True,
  'CYGOPT_NET_DHCP_DHCP_THREAD_PARAM': True,
  'CYGDBG_INFRA_DEBUG_TRACE_BUFFER_SIZE': True,
  'CYGNUM_UITRON_ISR_ACTION_QUEUESIZE': True,
  'CYGPKG_COMPRESS_ZLIB_LDFLAGS_ADD': True,
  'CYGSEM_LIBC_STDIO_THREAD_SAFE_STREAMS': False,
  'CYGPKG_UITRON_FLAGS': True,
  'CYGINT_ISO_STDLIB_ENVIRON': True,
  'CYGPKG_MEMALLOC': True,
  'CYGPKG_LIBC_STRING_STRTOK': False,
  'CYGPKG_INFRA_CFLAGS_REMOVE': True,
  'CYGBLD_ISO_SCHEDTYPES_HEADER': True,
  'CYGNUM_POSIX_MQUEUE_OPEN_MAX': True,
  'CYGPKG_NS_DNS': True,
  'CYGPKG_IO_ETH_DRIVERS_SIMULATE_DROP_RX': True,
  'CYGNUM_UITRON_MEMPOOLFIXED': True,
  'CYGSEM_WATCHDOG_RESETS_ON_TIMEOUT': True,
  'CYGINT_KERNEL_COUNTERS': True,
  'CYGIMP_HAL_COMMON_INTERRUPTS_USE_INTERRUPT_STACK': True,
  'CYGHWR_DEVS_FLASH_AMD_AM29F800': True,
  'CYGDBG_IO_DISK_DEBUG': True,
  'CYGNUM_POWER_THREAD_STACKSIZE': True,
  'CYGNUM_VNC_SERVER_FRAME_WIDTH': True,
  'CYGPKG_LIBC_I18N_CFLAGS_ADD': False,
  'CYGPKG_LIBC_STDIO_CFLAGS_ADD': False,
  'CYG_POSIX_UTSNAME_LENGTH': True,
  'CYGPKG_LIBC_TIME_OPTIONS': False,
  'CYGBLD_ISO_TERMIOS_HEADER': True,
  'CYGIMP_LIBC_STDLIB_INLINE_ABS': False,
  'CYGINT_ISO_SETJMP': True,
  'CYGPKG_LIBC_STDIO_FLOATING_POINT': False,
  'CYGPKG_POWER': True,
  'CYGIMP_KERNEL_INTERRUPTS_DSRS_TABLE': True,
  'CYGPKG_NET_FAST_THREAD': True,
  'CYGSEM_HAL_DIAG_MANGLER': True,
  'CYGSEM_LIBC_STDIO_WANT_BUFFERED_IO': False,
  'CYGPKG_LIBC_STARTUP_CFLAGS_ADD': False,
  'CYGVAR_KERNEL_COUNTERS_CLOCK_DSR_LATENCY': True,
  'CYGOPT_IO_SERIAL_SUPPORT_NONBLOCKING': True,
  'CYGNUM_UITRON_VER_PRNO_1': True,
  'CYGPKG_FS_RAM_TESTS': True,
  'CYGFUN_LIBC_STRING_STRDUP': False,
  '_POSIX_THREAD_ATTR_STACKADDR': True,
  'CYGSEM_HAL_STATIC_MMU_TABLES': True,
  'CYGPKG_DEVS_TOUCH_AAED2000': True,
  'CYGBLD_MEMALLOC_MALLOC_EXTERNAL_JOIN_H': True,
  'CYGPKG_HAL_ARM': True,
  'CYGVAR_KERNEL_THREADS_NAME': True,
  'CYGNUM_KERNEL_THREADS_DESTRUCTORS': True,
  'CYGBLD_ISO_CTYPE_HEADER': True,
  'CYGBLD_INFRA_CFLAGS_WARNINGS_AS_ERRORS': True,
  'CYGPKG_UITRON_MEMPOOLVAR': True,
  'CYGDBG_KERNEL_INSTRUMENT_MSGS_BUILD_HEADERFILE': True,
  'CYGPKG_KERNEL_TESTS': True,
  'CYGPKG_COMPRESS_ZLIB_LDFLAGS_REMOVE': True,
  'CYGHWR_DEVS_FLASH_AMD_S29GL128M': True,
  'CYGIMP_LIBC_TIME_DIFFTIME_INLINE': False,
  'CYGNUM_JFFS2_GS_THREAD_TICKS': True,
  'CYGOPT_HAL_ARM_WITH_USER_MODE': True,
  'CYGIMP_KERNEL_SCHED_SORTED_QUEUES': True,
  'CYGINT_ISO_CTYPE': True,
  'CYGPKG_HAL_ARM_ARM9_ARM940T': False,
  'CYGPKG_LIBC_SETJMP': False,
  'CYGNUM_KERNEL_THREADS_DATA_ALL': True,
  'CYGPKG_IO_WATCHDOG_OPTIONS': True,
  'CYGSEM_KERNEL_SYNCH_MUTEX_PRIORITY_INVERSION_PROTOCOL_DYNAMIC': False,
  'CYGPKG_IO_SERIAL_CFLAGS_REMOVE': True,
  'CYGNUM_LIBC_TIME_DST_DEFAULT_STATE': False,
  'CYGPKG_ISO_UTSNAME': True,
  'CYGHWR_MEMORY_LAYOUT': True,
  'CYGPKG_LIBC_RAND': False,
  'CYGOPT_HAL_ARM_SYSCALL_GPROF_SUPPORT': False,
  'CYGPKG_NET_CFLAGS_REMOVE': True,
  'CYGPKG_HTTPD_MONITOR': True,
  'CYGNUM_FILEIO_FSTAB_MAX': True,
  'CYGNUM_UITRON_VER_SPVER': True,
  'CYGBLD_ISO_CLOCK_T_HEADER': True,
  'CYGPKG_DEVS_ETH_CL_CS8900A_OPTIONS': True,
  'CYGDBG_KERNEL_INSTRUMENT_CLOCK': True,
  'CYGPKG_FS_FAT': True,
  'CYGNUM_HTTPD_THREAD_STACK_SIZE': True,
  'CYGPKG_NET_MEMPOOL_SIZE': True,
  'CYGOPT_FS_JFFS2_GCTHREAD': True,
  'CYGHWR_DEVS_FLASH_AMD_S29PL064J': True,
  'CYGINT_ISO_STDLIB_STRCONV': True,
  'CYGPKG_IO_FILEIO_SOCKET_SUPPORT': True,
  'CYGPKG_IO_NFILE': False,
  'CYGNUM_LIBC_TIME_STD_DEFAULT_OFFSET': False,
  'CYGNUM_HAL_RTC_DENOMINATOR': True,
  'CYGBLD_ISO_TIME_T_HEADER': True,
  'FOPEN_MAX': False,
  'CYGPKG_IO_ETH_DRIVERS_SIMULATE_DROP_TX': True,
  'CYGINT_ISO_STDIO_FILEACCESS': True,
  'CYGPKG_PPP_AUTH_DEFAULT_USER': True,
  'CYGSEM_ERROR_PER_THREAD_ERRNO': True,
  'CYGDAT_NET_SNMPAGENT_SYS_NAME': True,
  'CYGPKG_PPP_WORKAROUNDS': True,
  'CYGPKG_INFRA_TESTS': True,
  'CYGSEM_KERNEL_SCHED_ASR_DATA_GLOBAL': False,
  'CYGPKG_ISO_LOCALE': True,
  'CYGBLD_ISO_STDIO_CHAR_IO_HEADER': True,
  'CYGBLD_ISO_POSIX_LIMITS_HEADER': True,
  'CYGPKG_VNC_SERVER_BUILD_KEYBOARD_DRIVER': True,
  'CYGHWR_DEVS_FLASH_AMD_AM29F040B': True,
  'CYGPKG_ERROR_OPTIONS': True,
  'CYGSEM_SNMPAGENT_TESTS_PROMISCUOUS': True,
  'CYGCFG_FS_FAT_USE_ATTRIBUTES': True,
  'CYGSEM_LIBC_TIME_CLOCK_WORKING': False,
  'CYGNUM_KERNEL_THREADS_DATA_ITRON': True,
  'CYGSEM_IO_FLASH_CHATTER': True,
  'CYGOPT_FS_JFFS2_COMPRESS': True,
  'CYGIMP_LIBC_TIME_LOCALTIME_R_INLINE': False,
  'CYGBLD_HAL_LINKER_GROUPED_LIBS': True,
  'CYGBLD_ISO_STRING_BSD_FUNCS_HEADER': True,
  'CYGNUM_LINUX_COMPAT_PAGE_SIZE_EXPONENT': True,
  'CYGPKG_NET_STACK_INET6': True,
  'CYGSEM_FILEIO_INFO_DISK_USAGE': True,
  'CYGINT_WALLCLOCK_SET_GET_MODE_SUPPORTED': True,
  'CYGINT_HAL_ARM_ARM9_VARIANT': True,
  'CYGPKG_HAL_ARM_ARM9_AAED2000_OPTIONS': True,
  'CYGNUM_UITRON_VER_VAR': True,
  'CYGPKG_LIBC_I18N_LOCALES': False,
  'CYGPKG_FS_RAM_RET_DIRENT_DTYPE': True,
  'CYGHWR_REDBOOT_ARM_LINUX_EXEC_ADDRESS': False,
  'CYGPKG_IO_FILEIO_DEVFS_SUPPORT': True,
  'CYGPKG_NET_FREEBSD_STACK_OPTIONS': True,
  'CYGPKG_FS_RAM_BLOCKS_ARRAY_EXTERN': True,
  'CYGIMP_LIBC_RAND_SIMPLE1': False,
  'CYGPKG_LIBC_STDIO_CFLAGS_REMOVE': False,
  'CYGSEM_LIBC_INVOKE_DEFAULT_STATIC_CONSTRUCTORS': False,
  'CYGNUM_KERNEL_INSTRUMENT_BUFFER_SIZE': True,
  'CYGINT_IO_ETH_MULTICAST': True,
  'CYGINT_ISO_C_CLOCK_FUNCS': True,
  'CYGPKG_UITRON_OPTIONS': True,
  'CYGPKG_UITRON_SEMAS_ARE_INITIALIZED': True,
  'CYGNUM_UITRON_MEMPOOLVAR_INITIALLY': True,
  'CYGPKG_FS_ROM_RET_DIRENT_DTYPE': True,
  'CYGBLD_ISO_ASSERT_HEADER': True,
  'CYGHWR_DEVS_FLASH_AMD_AM29DL323D': True,
  'CYGINT_ISO_SIGNAL_IMPL': True,
  'CYGBLD_ISO_BSDTYPES_HEADER': True,
  'CYGPKG_ISO_TIME': True,
  'CYGINT_ISO_MALLOC': True,
  'CYGPKG_NET_IPSEC': True,
  'CYGINT_POSIX_REALTIME_SIGNALS': True,
  'CYGBLD_ISO_NETDB_PROTO_HEADER': True,
  'CYGPKG_LIBC_TIME_ZONES': False,
  'CYGNUM_HAL_COMMON_INTERRUPTS_STACK_SIZE': True,
  'CYGPKG_SNMPLIB_PERSISTENT_FILESYSTEM': True,
  'CYGIMP_LIBC_TIME_GMTIME_INLINE': False,
  'CYGPKG_KERNEL_EXCEPTIONS': True,
  'CYGPKG_WALLCLOCK_EMULATE_alt': True,
  'CYGSEM_COMPRESS_ZLIB_NEEDS_MALLOC': False,
  'CYGIMP_LIBC_STRING_PREFER_SMALL_TO_FAST': False,
  'CYGHWR_NET_DRIVER_ETH1_SETUP': False,
  'CYGIMP_POWER_PROVIDE_STRINGS': True,
  'CYGPKG_ISO_POSIX_FCNTL': True,
  'CYGNUM_KERNEL_THREADS_DATA_POSIX': True,
  'CYGHWR_DEVS_FLASH_AMD_AM29LV800': True,
  'CYGDBG_INFRA_DEBUG_TRACE_MESSAGE': True,
  'CYGHWR_DEVS_FLASH_AMD_S29GL128N': True,
  'CYGIMP_KERNEL_COUNTERS_SINGLE_LIST_alt': True,
  'CYGDBG_INFRA_DEBUG_TRACE_ASSERT_NULL': False,
  'CYGHWR_NET_DRIVER_ETH0': True,
  'CYGSEM_KERNEL_SCHED_TIMESLICE_ENABLE': True,
  'CYGSEM_KERNEL_SCHED_ASR_SUPPORT': True,
  'CYGPKG_REDBOOT_ARM_OPTIONS': False,
  'CYGPKG_NET_FREEBSD_STACK_CFLAGS_ADD': True,
  'CYGPKG_HAL_ARM_ARM9_ARM920T_alt': True,
  'CYGBLD_ISO_STDLIB_DIV_HEADER': True,
  'CYGPKG_UITRON_MEMPOOLFIXED': True,
  'CYGDBG_HAL_DEBUG_GDB_CTRLC_SUPPORT': False,
  'CYGPKG_NET_FREEBSD_STACK_CFLAGS_REMOVE': True,
  'CYGHWR_NET_DRIVER_ETH0_IPV6_PREFIX': True,
  'CYGINT_HAL_ARM_ARCH_ARM7': True,
  'CYGOPT_PPP_NS_NEGOTIATE': True,
  'CYGDBG_HAL_COMMON_CONTEXT_SAVE_MINIMUM': True,
  'CYGHWR_THUMB': True,
  '_POSIX_THREAD_PRIORITY_SCHEDULING': True,
  'CYGPKG_POSIX_PTHREAD_REQUIREMENTS': True,
  'CYGPKG_KERNEL_CFLAGS_ADD': True,
  'CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_DEFAULT': True,
  'CYGPKG_PPP_OPTIONS': True,
  'CYGNUM_MEMALLOC_ALLOCATOR_DLMALLOC_ALIGNMENT': True,
  'CYGINT_KERNEL_SYNCH_MUTEX_PRIORITY_INVERSION_PROTOCOL_COUNT': False,
  'CYGSEM_UITRON_PARAMS_NULL_IS_GOOD_PTR': True,
  'CYGINT_ISO_SCHED_IMPL': True,
  'CYGBLD_IO_SERIAL_EXTRA_TESTS': True,
  'CYGNUM_VNC_SERVER_CORRE_ENCODING_HACK': True,
  'CYGPKG_NET_FREEBSD_SYSCTL': True,
  'CYGHWR_DEVS_FLASH_AMD_AM29DL640D': True,
  'CYGPKG_NET_FREEBSD_STACK': True,
  'CYGBLD_ISO_SEMAPHORES_HEADER': True,
  'CYGNUM_UITRON_VER_ID': True,
  'CYGNUM_LIBC_STDIO_BUFSIZE': False,
  'CYGBLD_ISO_SIGNAL_IMPL_HEADER': True,
  'CYGFUN_MEMALLOC_KAPI': True,
  'CYGPKG_NET_FREEBSD_STACK_TESTS': True,
  'CYGNUM_VNC_SERVER_INCLUDE_VNC_PRINTF': True,
  'CYGPKG_KERNEL_THREADS_DESTRUCTORS': True,
  'CYGHWR_DEVS_FLASH_AMD_AM29LV065D': True,
  'CYGINT_HAL_DEBUG_GDB_CTRLC_UNSUPPORTED': True,
  'CYGDAT_VNC_DESKTOP_NAME': True,
  'CYGFUN_LIBM_SVID3_scalb': True,
  'CYGPKG_FS_ROM': True,
  'CYGBLD_ARM_ENABLE_THUMB_INTERWORK': True,
  'CYGDAT_IO_FLASH_BLOCK_FIS_NAME_2': True,
  'CYGINT_IO_SERIAL_TEST_SKIP_57600': True,
  'CYGPKG_HTTPD_CFLAGS_REMOVE': True,

In [13]:
instance = get_instance("busybox_2007-01-24_09-14-09", INSTANCE_ARCHIVE)
instance.instance_name

Parsing DIMACS

'models/busybox_2007-01-24_09-14-09'

In [14]:
instance.rules

[OR(VAR[CONFIG_FDISK], NVAR[CONFIG_FEATURE_AIX_LABEL]),
 OR(VAR[CONFIG_FEATURE_HTTPD_CGI], NVAR[CONFIG_FEATURE_HTTPD_CONFIG_WITH_SCRIPT_INTERPR]),
 OR(VAR[CONFIG_FEATURE_IFUPDOWN_IP], NVAR[CONFIG_FEATURE_IFUPDOWN_IP_BUILTIN]),
 OR(NVAR[CONFIG_FEATURE_HTTPD_BASIC_AUTH], VAR[CONFIG_HTTPD]),
 OR(NVAR[CONFIG_FEATURE_LS_COLOR_IS_DEFAULT], VAR[CONFIG_FEATURE_LS_COLOR]),
 OR(VAR[CONFIG_FEATURE_SYSLOG], NVAR[CONFIG_ZCIP]),
 OR(VAR[CONFIG_FEATURE_SYSLOG], NVAR[CONFIG_INETD]),
 OR(NVAR[CONFIG_FEATURE_INSMOD_LOAD_MAP], VAR[CONFIG_INSMOD]),
 OR(NVAR[CONFIG_LOGGER], VAR[CONFIG_FEATURE_SYSLOG]),
 OR(VAR[CONFIG_FEATURE_SUID], NVAR[CONFIG_CROND]),
 OR(NVAR[CONFIG_FEATURE_LESS_FLAGCS], VAR[CONFIG_LESS]),
 OR(NVAR[CONFIG_CROND], VAR[CONFIG_FEATURE_SYSLOG]),
 OR(NVAR[CONFIG_FEATURE_RUN_PARTS_LONG_OPTIONS], VAR[CONFIG_GETOPT_LONG]),
 OR(NVAR[CONFIG_FEATURE_REMOTE_LOG], VAR[CONFIG_SYSLOGD]),
 OR(NVAR[CONFIG_FEATURE_MD5_SHA1_SUM_CHECK], VAR[CONFIG_SHA1SUM], VAR[CONFIG_MD5SUM]),
 OR(NVAR[CONFIG_EFENCE], VAR[CONFIG_DEBUG]),
 OR(VAR[CONFIG_MODPROBE], NVAR[CONFIG_FEATURE_MODPROBE_MULTIPLE_OPTIONS]),
 OR(NVAR[CONFIG_EFENCE], NVAR[CONFIG_NO_DEBUG_LIB]),
 OR(NVAR[CONFIG_FEATURE_IP_ROUTE], NVAR[CONFIG_FEATURE_IP_SHORT_FORMS], VAR[CONFIG_IPROUTE]),
 OR(VAR[CONFIG_FIND], NVAR[CONFIG_FEATURE_FIND_INUM]),
 OR(NVAR[CONFIG_FEATURE_GREP_CONTEXT], VAR[CONFIG_GREP]),
 OR(NVAR[CONFIG_FEATURE_LESS_FLAGS], VAR[CONFIG_LESS]),
 OR(VAR[CONFIG_HTTPD], NVAR[CONFIG_FEATURE_HTTPD_CONFIG_WITH_MIME_TYPES]),
 OR(NVAR[CONFIG_LASH], VAR[CONFIG_TRUE]),
 OR(VAR[CONFIG_LS], NVAR[CONFIG_FEATURE_LS_COLOR], VAR[CONFIG_GETOPT_LONG]),
 OR(VAR[CONFIG_FEATURE_WTMP], NVAR[CONFIG_LAST]),
 OR(NVAR[CONFIG_INSTALL_APPLET_DONT], NVAR[CONFIG_INSTALL_APPLET_SYMLINKS]),
 OR(NVAR[CONFIG_FEATURE_BUFFERS_GO_IN_BSS], NVAR[CONFIG_FEATURE_BUFFERS_USE_MALLOC]),
 OR(NVAR[CONFIG_FEATURE_TAR_CREATE], VAR[CONFIG_TAR]),
 OR(NVAR[CONFIG_WATCH], VAR[CONFIG_DATE]),
 OR(NVAR[CONFIG_FEATURE_FIND_PRINT0], VAR[CONFIG_FIND]),
 OR(VAR[CONFIG_IP], VAR[CONFIG_FEATURE_IP_ADDRESS], NVAR[CONFIG_FEATURE_IFUPDOWN_IP_BUILTIN]),
 OR(NVAR[CONFIG_FEATURE_HTTPD_RELOAD_CONFIG_SIGHUP], VAR[CONFIG_HTTPD]),
 OR(NVAR[CONFIG_FEATURE_HTTPD_CGI], VAR[CONFIG_HTTPD]),
 OR(NVAR[CONFIG_FEATURE_IP_ROUTE], VAR[CONFIG_IP], VAR[CONFIG_FEATURE_IFUPDOWN_IP_BUILTIN]),
 OR(NVAR[CONFIG_FEATURE_SUN_LABEL], VAR[CONFIG_FDISK]),
 OR(NVAR[CONFIG_FEATURE_MAKEDEVS_LEAF], VAR[CONFIG_MAKEDEVS]),
 OR(NVAR[CONFIG_FEATURE_TAR_FROM], VAR[CONFIG_TAR]),
 OR(NVAR[CONFIG_FEATURE_VERBOSE_USAGE], VAR[CONFIG_SHOW_USAGE]),
 OR(NVAR[CONFIG_FEATURE_SH_IS_LASH], NVAR[CONFIG_FEATURE_SH_IS_HUSH]),
 OR(NVAR[CONFIG_LOGIN_SCRIPTS], VAR[CONFIG_LOGIN]),
 OR(VAR[CONFIG_FEATURE_FDISK_WRITABLE], NVAR[CONFIG_FEATURE_OSF_LABEL]),
 OR(NVAR[CONFIG_FEATURE_FANCY_PING], VAR[CONFIG_PING]),
 OR(VAR[CONFIG_FEATURE_IP_SHORT_FORMS], NVAR[CONFIG_IPLINK]),
 OR(VAR[CONFIG_VI], NVAR[CONFIG_FEATURE_VI_DOT_CMD]),
 OR(VAR[CONFIG_ASH], NVAR[CONFIG_ASH_CMDCMD]),
 OR(NVAR[CONFIG_DMALLOC], NVAR[CONFIG_NO_DEBUG_LIB]),
 OR(VAR[CONFIG_FEATURE_SH_IS_ASH], VAR[CONFIG_FEATURE_SH_IS_LASH], VAR[CONFIG_FEATURE_SH_IS_HUSH], VAR[CONFIG_FEATURE_SH_IS_NONE], VAR[CONFIG_FEATURE_SH_IS_MSH]),
 OR(NVAR[CONFIG_FEATURE_MOUNT_NFS], VAR[CONFIG_FEATURE_SYSLOG]),
 OR(NVAR[CONFIG_FEATURE_FANCY_ECHO], VAR[CONFIG_ECHO]),
 OR(NVAR[CONFIG_FEATURE_MKDIR_LONG_OPTIONS], VAR[CONFIG_GETOPT_LONG]),
 OR(VAR[CONFIG_READLINK], NVAR[CONFIG_FEATURE_READLINK_FOLLOW]),
 OR(VAR[CONFIG_ASH], NVAR[CONFIG_ASH_EXPAND_PRMT]),
 OR(NVAR[CONFIG_FEATURE_DEB_TAR_LZMA], VAR[CONFIG_DPKG_DEB], VAR[CONFIG_DPKG]),
 OR(NVAR[CONFIG_FEATURE_UDHCP_SYSLOG], VAR[CONFIG_FEATURE_SYSLOG]),
 OR(NVAR[CONFIG_FEATURE_INETD_SUPPORT_BUILTIN_DISCARD], VAR[CONFIG_INETD]),
 OR(NVAR[CONFIG_FEATURE_IFUPDOWN_IFCONFIG_BUILTIN], NVAR[CONFIG_FEATURE_IFUPDOWN_IP]),
 OR(VAR[CONFIG_LESS], NVAR[CONFIG_FEATURE_LESS_MARKS]),
 OR(NVAR[CONFIG_LESS], VAR[CONFIG_FEATURE_LESS_MAXLINES]),
 OR(NVAR[CONFIG_FEATURE_INETD_SUPPORT_BUILTIN_TIME], VAR[CONFIG_INETD]),
 OR(NVAR[CONFIG_FEATURE_TOP_CPU_USAGE_PERCENTAGE], VAR[CONFIG_TOP]),
 OR(NVAR[CONFIG_FEATURE_INETD_SUPPORT_BUILTIN_CHARGEN], VAR[CONFIG_INETD]),
 OR(NVAR[CONFIG_FEATURE_BUFFERS_GO_ON_STACK], NVAR[CONFIG_FEATURE_BUFFERS_USE_MALLOC]),
 OR(NVAR[CONFIG_FEATURE_HWCLOCK_LONG_OPTIONS], VAR[CONFIG_GETOPT_LONG]),
 OR(NVAR[CONFIG_LOGIN], VAR[CONFIG_FEATURE_SYSLOG]),
 OR(VAR[CONFIG_FEATURE_SHADOWPASSWDS], VAR[CONFIG_USE_BB_PWD_GRP], NVAR[CONFIG_USE_BB_SHADOW]),
 OR(VAR[CONFIG_KILL], NVAR[CONFIG_KILLALL]),
 OR(VAR[CONFIG_INIT], NVAR[CONFIG_FEATURE_INIT_SCTTY]),
 OR(NVAR[CONFIG_MSH], VAR[CONFIG_FALSE]),
 OR(NVAR[CONFIG_FEATURE_WTMP], VAR[CONFIG_LAST], VAR[CONFIG_LOGIN], VAR[CONFIG_SU], VAR[CONFIG_GETTY]),
 OR(VAR[CONFIG_DF], VAR[CONFIG_LS], VAR[CONFIG_DU], NVAR[CONFIG_FEATURE_HUMAN_READABLE]),
 OR(VAR[CONFIG_FEATURE_UTMP], NVAR[CONFIG_WHO], NVAR[CONFIG_SU]),
 OR(VAR[CONFIG_ASH], NVAR[CONFIG_ASH_JOB_CONTROL]),
 OR(VAR[CONFIG_FEATURE_UTMP], NVAR[CONFIG_WHO], NVAR[CONFIG_LOGIN]),
 OR(NVAR[CONFIG_FEATURE_BUFFERS_GO_ON_STACK], NVAR[CONFIG_FEATURE_BUFFERS_GO_IN_BSS]),
 OR(VAR[CONFIG_FEATURE_IPV6], NVAR[CONFIG_FEATURE_IFUPDOWN_IPV6]),
 OR(VAR[CONFIG_KILL], NVAR[CONFIG_KILLALL5]),
 OR(NVAR[CONFIG_FEATURE_VI_COLON], VAR[CONFIG_VI]),
 OR(VAR[CONFIG_LASH], VAR[CONFIG_ASH], VAR[CONFIG_MSH], VAR[CONFIG_HUSH], NVAR[CONFIG_FEATURE_SH_EXTRA_QUIET]),
 OR(NVAR[CONFIG_FEATURE_MOUNT_LOOP], VAR[CONFIG_MOUNT], VAR[CONFIG_UMOUNT]),
 OR(VAR[CONFIG_BUILD_LIBBUSYBOX], NVAR[CONFIG_FEATURE_FULL_LIBBUSYBOX]),
 OR(NVAR[CONFIG_FEATURE_SH_IS_LASH], NVAR[CONFIG_FEATURE_SH_IS_MSH]),
 OR(VAR[CONFIG_IFUPDOWN], NVAR[CONFIG_FEATURE_IFUPDOWN_IPV4]),
 OR(NVAR[CONFIG_FEATURE_SUID_CONFIG_QUIET], VAR[CONFIG_FEATURE_SUID_CONFIG]),
 OR(NVAR[CONFIG_FEATURE_CHECK_TAINTED_MODULE], VAR[CONFIG_INSMOD], VAR[CONFIG_LSMOD]),
 OR(VAR[CONFIG_INSMOD], NVAR[CONFIG_FEATURE_INSMOD_KSYMOOPS_SYMBOLS]),
 OR(NVAR[CONFIG_IP], VAR[CONFIG_FEATURE_IP_ADDRESS], NVAR[CONFIG_FEATURE_IFUPDOWN_IP_BUILTIN]),
 OR(VAR[CONFIG_BUILD_LIBBUSYBOX], NVAR[CONFIG_STATIC], NVAR[CONFIG_FEATURE_SHARED_BUSYBOX]),
 OR(NVAR[CONFIG_SULOGIN], VAR[CONFIG_FEATURE_SYSLOG]),
 OR(VAR[CONFIG_PING6], NVAR[CONFIG_FEATURE_FANCY_PING6]),
 OR(VAR[CONFIG_TEST], NVAR[CONFIG_MSH]),
 OR(NVAR[CONFIG_LFS], VAR[CONFIG_FDISK], VAR[CONFIG_FDISK_SUPPORT_LARGE_DISKS]),
 OR(VAR[CONFIG_MORE], VAR[CONFIG_TELNET], VAR[CONFIG_LS], NVAR[CONFIG_FEATURE_AUTOWIDTH]),
 OR(VAR[CONFIG_FEATURE_SUID], NVAR[CONFIG_FEATURE_SUID_CONFIG]),
 OR(NVAR[CONFIG_FEATURE_DPKG_DEB_EXTRACT_ONLY], VAR[CONFIG_DPKG_DEB]),
 OR(VAR[CONFIG_FEATURE_TAB_COMPLETION], NVAR[CONFIG_FEATURE_USERNAME_COMPLETION]),
 OR(VAR[CONFIG_HDPARM], NVAR[CONFIG_FEATURE_HDPARM_HDIO_GETSET_DMA]),
 OR(VAR[CONFIG_HDPARM], NVAR[CONFIG_FEATURE_HDPARM_HDIO_DRIVE_RESET]),
 OR(NVAR[CONFIG_LFS], NVAR[CONFIG_FDISK], VAR[CONFIG_FDISK_SUPPORT_LARGE_DISKS]),
 OR(NVAR[CONFIG_FEATURE_SH_IS_ASH], NVAR[CONFIG_FEATURE_SH_IS_LASH]),
 OR(NVAR[CONFIG_FEATURE_WGET_LONG_OPTIONS], VAR[CONFIG_GETOPT_LONG]),
 OR(NVAR[CONFIG_FEATURE_HDPARM_HDIO_UNREGISTER_HWIF], VAR[CONFIG_HDPARM]),
 OR(NVAR[CONFIG_FEATURE_FANCY_SLEEP], VAR[CONFIG_SLEEP]),
 OR(NVAR[CONFIG_FEATURE_MODPROBE_FANCY_ALIAS], VAR[CONFIG_FEATURE_2_6_MODULES], VAR[CONFIG_NITPICK]),
 OR(VAR[CONFIG_FEATURE_HAVE_RPC], NVAR[CONFIG_FEATURE_INETD_RPC]),
 OR(NVAR[CONFIG_FEATURE_2_6_MODULES], NVAR[CONFIG_FEATURE_QUERY_MODULE_INTERFACE]),
 OR(VAR[CONFIG_FEATURE_WTMP], NVAR[CONFIG_FEATURE_UTMP], VAR[CONFIG_WHO], VAR[CONFIG_LOGIN], VAR[CONFIG_SU], VAR[CONFIG_GETTY]),
 OR(VAR[CONFIG_MKSWAP], NVAR[CONFIG_FEATURE_MKSWAP_V0]),
 OR(VAR[CONFIG_INSMOD], NVAR[CONFIG_FEATURE_INSMOD_VERSION_CHECKING]),
 OR(NVAR[CONFIG_FEATURE_SU_SYSLOG], VAR[CONFIG_SU]),
 OR(VAR[CONFIG_STAT], NVAR[CONFIG_FEATURE_STAT_FORMAT]),
 OR(VAR[CONFIG_IP], NVAR[CONFIG_FEATURE_IP_SHORT_FORMS]),
 OR(VAR[CONFIG_FEATURE_2_6_MODULES], NVAR[CONFIG_FEATURE_2_4_MODULES], VAR[CONFIG_FEATURE_QUERY_MODULE_INTERFACE]),
 OR(NVAR[CONFIG_FEATURE_WGET_STATUSBAR], VAR[CONFIG_WGET]),
 OR(NVAR[CONFIG_FEATURE_TAR_GZIP], VAR[CONFIG_TAR]),
 OR(NVAR[CONFIG_FEATURE_INSMOD_LOAD_MAP], VAR[CONFIG_FEATURE_2_6_MODULES], VAR[CONFIG_FEATURE_2_4_MODULES]),
 OR(NVAR[CONFIG_STATIC], NVAR[CONFIG_FEATURE_SHARED_BUSYBOX]),
 OR(NVAR[CONFIG_FEATURE_INSMOD_LOADINKMEM], VAR[CONFIG_INSMOD]),
 OR(NVAR[CONFIG_FEATURE_PASSWD_WEAK_CHECK], VAR[CONFIG_PASSWD]),
 OR(NVAR[CONFIG_FEATURE_FIND_PERM], VAR[CONFIG_FIND]),
 OR(VAR[CONFIG_FEATURE_IP_LINK], VAR[CONFIG_IP], NVAR[CONFIG_FEATURE_IFUPDOWN_IP_BUILTIN]),
 OR(NVAR[CONFIG_FEATURE_WTMP], VAR[CONFIG_FEATURE_UTMP], VAR[CONFIG_WHO], VAR[CONFIG_LOGIN], VAR[CONFIG_SU], VAR[CONFIG_GETTY]),
 OR(NVAR[CONFIG_FEATURE_IPC_SYSLOG], VAR[CONFIG_SYSLOGD]),
 OR(VAR[CONFIG_LS], NVAR[CONFIG_FEATURE_LS_RECURSIVE]),
 OR(VAR[CONFIG_IFCONFIG], NVAR[CONFIG_FEATURE_IFCONFIG_SLIP]),
 OR(VAR[CONFIG_FEATURE_IP_ADDRESS], NVAR[CONFIG_FEATURE_IFUPDOWN_IP_BUILTIN]),
 OR(VAR[CONFIG_FIND], NVAR[CONFIG_FEATURE_FIND_EXEC]),
 OR(VAR[CONFIG_IPADDR], NVAR[CONFIG_FEATURE_IP_SHORT_FORMS], NVAR[CONFIG_FEATURE_IP_ADDRESS]),
 OR(VAR[CONFIG_DMESG], NVAR[CONFIG_FEATURE_DMESG_PRETTY]),
 OR(VAR[CONFIG_PASSWORD_MINLEN]),
 OR(NVAR[CONFIG_FEATURE_MAKEDEVS_TABLE], VAR[CONFIG_MAKEDEVS]),
 OR(VAR[CONFIG_GUNZIP], NVAR[CONFIG_FEATURE_GUNZIP_UNCOMPRESS]),
 OR(NVAR[CONFIG_DEVFSD_MODLOAD], VAR[CONFIG_DEVFSD]),
 OR(VAR[CONFIG_IPRULE], NVAR[CONFIG_FEATURE_IP_RULE], NVAR[CONFIG_FEATURE_IP_SHORT_FORMS]),
 OR(NVAR[CONFIG_FEATURE_INIT_COREDUMPS], VAR[CONFIG_INIT]),
 OR(NVAR[CONFIG_FEATURE_IP_LINK], VAR[CONFIG_IP], VAR[CONFIG_FEATURE_IFUPDOWN_IP_BUILTIN]),
 OR(NVAR[CONFIG_FEATURE_FTPGETPUT_LONG_OPTIONS], VAR[CONFIG_GETOPT_LONG]),
 OR(VAR[CONFIG_MV], VAR[CONFIG_CP], NVAR[CONFIG_FEATURE_PRESERVE_HARDLINKS]),
 OR(NVAR[CONFIG_FEATURE_MODPROBE_FANCY_ALIAS], VAR[CONFIG_FEATURE_2_6_MODULES], VAR[CONFIG_MODPROBE]),
 OR(NVAR[CONFIG_FEATURE_XARGS_SUPPORT_CONFIRMATION], VAR[CONFIG_XARGS]),
 OR(VAR[CONFIG_FEATURE_WTMP], NVAR[CONFIG_LAST], NVAR[CONFIG_SU]),
 OR(NVAR[CONFIG_FEATURE_LS_TIMESTAMPS], VAR[CONFIG_LS]),
 OR(NVAR[CONFIG_FEATURE_FIND_XDEV], VAR[CONFIG_FIND]),
 OR(NVAR[CONFIG_IPRULE], VAR[CONFIG_FEATURE_IP_RULE]),
 OR(VAR[CONFIG_VI], NVAR[CONFIG_FEATURE_VI_READONLY]),
 OR(VAR[CONFIG_WC], NVAR[CONFIG_FEATURE_WC_LARGE]),
 OR(VAR[CONFIG_FEATURE_EDITING], NVAR[CONFIG_FEATURE_EDITING_VI]),
 OR(VAR[CONFIG_MSH], NVAR[CONFIG_FEATURE_SH_IS_MSH]),
 OR(VAR[CONFIG_ASH], NVAR[CONFIG_ASH_RANDOM_SUPPORT]),
 OR(VAR[CONFIG_ASH], NVAR[CONFIG_FEATURE_SH_IS_ASH]),
 OR(NVAR[CONFIG_ASH], VAR[CONFIG_TEST]),
 OR(VAR[CONFIG_FEATURE_MAKEDEVS_TABLE], VAR[CONFIG_FEATURE_MAKEDEVS_LEAF], NVAR[CONFIG_MAKEDEVS]),
 OR(VAR[CONFIG_FEATURE_2_4_MODULES], NVAR[CONFIG_FEATURE_QUERY_MODULE_INTERFACE]),
 OR(VAR[CONFIG_TFTP], NVAR[CONFIG_FEATURE_TFTP_BLOCKSIZE]),
 OR(NVAR[CONFIG_FEATURE_WGET_LONG_OPTIONS], VAR[CONFIG_WGET]),
 OR(VAR[CONFIG_ASH], NVAR[CONFIG_ASH_BUILTIN_TEST]),
 OR(VAR[CONFIG_DEBUG], NVAR[CONFIG_NO_DEBUG_LIB]),
 OR(NVAR[CONFIG_FEATURE_TAR_LONG_OPTIONS], VAR[CONFIG_TAR]),
 OR(NVAR[CONFIG_FEATURE_DD_IBS_OBS], VAR[CONFIG_DD]),
 OR(NVAR[CONFIG_DMALLOC], NVAR[CONFIG_EFENCE]),
 OR(VAR[CONFIG_FEATURE_SUID], NVAR[CONFIG_CRONTAB]),
 OR(NVAR[CONFIG_FEATURE_VI_WIN_RESIZE], VAR[CONFIG_VI]),
 OR(NVAR[CONFIG_LASH], VAR[CONFIG_TEST]),
 OR(NVAR[CONFIG_DMALLOC], VAR[CONFIG_DEBUG]),
 OR(NVAR[CONFIG_FEATURE_BUFFERS_GO_IN_BSS], VAR[CONFIG_NITPICK]),
 OR(NVAR[CONFIG_FEATURE_SH_IS_NONE], NVAR[CONFIG_FEATURE_SH_IS_MSH]),
 OR(VAR[CONFIG_TEE], NVAR[CONFIG_FEATURE_TEE_USE_BLOCK_IO]),
 OR(VAR[CONFIG_FEATURE_IP_LINK], NVAR[CONFIG_IP], NVAR[CONFIG_FEATURE_IFUPDOWN_IP_BUILTIN]),
 OR(VAR[CONFIG_TEST], NVAR[CONFIG_HUSH]),
 OR(NVAR[CONFIG_INIT], VAR[CONFIG_FEATURE_SYSLOG]),
 OR(NVAR[CONFIG_FEATURE_INSTALL_LONG_OPTIONS], VAR[CONFIG_INSTALL]),
 OR(NVAR[CONFIG_FEATURE_DEB_TAR_GZ], VAR[CONFIG_DPKG_DEB], VAR[CONFIG_DPKG]),
 OR(VAR[CONFIG_TEST], NVAR[CONFIG_FEATURE_TEST_64]),
 OR(VAR[CONFIG_LESS], NVAR[CONFIG_FEATURE_LESS_MAXLINES]),
 OR(VAR[CONFIG_UNIX2DOS], NVAR[CONFIG_DOS2UNIX]),
 OR(NVAR[CONFIG_FEATURE_LZMA_FAST], VAR[CONFIG_UNLZMA]),
 OR(NVAR[CONFIG_FEATURE_MOUNT_NFS], VAR[CONFIG_FEATURE_HAVE_RPC]),
 OR(NVAR[CONFIG_FEATURE_MODPROBE_FANCY_ALIAS], VAR[CONFIG_FEATURE_2_6_MODULES]),
 OR(NVAR[CONFIG_NAMEIF], VAR[CONFIG_FEATURE_SYSLOG]),
 OR(VAR[CONFIG_BUSYBOX_EXEC_PATH]),
 OR(VAR[CONFIG_PREFIX]),
 OR(NVAR[CONFIG_FEATURE_USE_INITTAB], VAR[CONFIG_INIT]),
 OR(VAR[CONFIG_FEATURE_WTMP], NVAR[CONFIG_LAST], NVAR[CONFIG_LOGIN]),
 OR(VAR[CONFIG_FDISK], NVAR[CONFIG_FEATURE_FDISK_ADVANCED]),
 OR(VAR[CONFIG_FEATURE_SUID], NVAR[CONFIG_VLOCK]),
 OR(VAR[CONFIG_HTTPD], NVAR[CONFIG_FEATURE_HTTPD_ENCODE_URL_STR]),
 OR(VAR[CONFIG_FEATURE_FDISK_WRITABLE], NVAR[CONFIG_FEATURE_FDISK_ADVANCED]),
 OR(VAR[CONFIG_FEATURE_SUID], NVAR[CONFIG_IPCRM]),
 OR(VAR[CONFIG_DU], NVAR[CONFIG_FEATURE_DU_DEFAULT_BLOCKSIZE_1K]),
 OR(VAR[CONFIG_VI], NVAR[CONFIG_FEATURE_VI_SET]),
 OR(VAR[CONFIG_FEATURE_IP_LINK], NVAR[CONFIG_IPLINK]),
 OR(NVAR[CONFIG_FEATURE_MODPROBE_FANCY_ALIAS], VAR[CONFIG_MODPROBE]),
 OR(VAR[CONFIG_FEATURE_SUID], NVAR[CONFIG_PASSWD]),
 OR(NVAR[CONFIG_FEATURE_TRACEROUTE_USE_ICMP], VAR[CONFIG_TRACEROUTE]),
 OR(VAR[CONFIG_FEATURE_EDITING], NVAR[CONFIG_FEATURE_EDITING_HISTORY]),
 OR(VAR[CONFIG_FDISK], NVAR[CONFIG_FEATURE_OSF_LABEL]),
 OR(NVAR[CONFIG_FEATURE_INSMOD_LOADINKMEM], VAR[CONFIG_FEATURE_2_4_MODULES]),
 OR(NVAR[CONFIG_FEATURE_CLEAN_UP], VAR[CONFIG_NITPICK]),
 OR(NVAR[CONFIG_FEATURE_PIDOF_SINGLE], VAR[CONFIG_PIDOF]),
 OR(NVAR[CONFIG_IPTUNNEL], VAR[CONFIG_FEATURE_IP_SHORT_FORMS]),
 OR(VAR[CONFIG_PS], NVAR[CONFIG_FEATURE_PS_WIDE]),
 OR(NVAR[CONFIG_MSH], VAR[CONFIG_TRUE]),
 OR(NVAR[CONFIG_FEATURE_SU_CHECKS_SHELLS], VAR[CONFIG_SU]),
 OR(VAR[CONFIG_EXPR], NVAR[CONFIG_EXPR_MATH_SUPPORT_64]),
 OR(NVAR[CONFIG_FEATURE_IFUPDOWN_IFCONFIG_BUILTIN], VAR[CONFIG_ROUTE]),
 OR(NVAR[CONFIG_FEATURE_WTMP], VAR[CONFIG_FEATURE_UTMP], NVAR[CONFIG_WHO]),
 OR(NVAR[CONFIG_FEATURE_XARGS_SUPPORT_ZERO_TERM], VAR[CONFIG_XARGS]),
 OR(VAR[CONFIG_AWK], NVAR[CONFIG_FEATURE_AWK_MATH]),
 OR(VAR[CONFIG_GREP], NVAR[CONFIG_FEATURE_GREP_FGREP_ALIAS]),
 OR(VAR[CONFIG_MODPROBE], NVAR[CONFIG_FEATURE_MODPROBE_MULTIPLE_OPTIONS], VAR[CONFIG_NITPICK]),
 OR(VAR[CONFIG_FEATURE_SYSLOG], NVAR[CONFIG_GETTY]),
 OR(VAR[CONFIG_FEATURE_FDISK_WRITABLE], NVAR[CONFIG_FEATURE_AIX_LABEL]),
 OR(NVAR[CONFIG_DEBUG_CROND_OPTION], VAR[CONFIG_CROND]),
 OR(VAR[CONFIG_APP_UDHCPD], NVAR[CONFIG_APP_DUMPLEASES]),
 OR(NVAR[CONFIG_FEATURE_SORT_BIG], VAR[CONFIG_SORT]),
 OR(NVAR[CONFIG_FEATURE_MDEV_EXEC], VAR[CONFIG_FEATURE_MDEV_CONF]),
 OR(NVAR[CONFIG_IPADDR], VAR[CONFIG_FEATURE_IP_ADDRESS]),
 OR(VAR[CONFIG_GETOPT_LONG], NVAR[CONFIG_FEATURE_ENV_LONG_OPTIONS]),
 OR(NVAR[CONFIG_INSTALL_APPLET_DONT], NVAR[CONFIG_INSTALL_APPLET_HARDLINKS]),
 OR(NVAR[CONFIG_FEATURE_INSTALL_LONG_OPTIONS], VAR[CONFIG_GETOPT_LONG]),
 OR(VAR[CONFIG_FEATURE_IP_ROUTE], VAR[CONFIG_IP], NVAR[CONFIG_FEATURE_IFUPDOWN_IP_BUILTIN]),
 OR(VAR[CONFIG_FTPGET], NVAR[CONFIG_FEATURE_FTPGETPUT_LONG_OPTIONS], VAR[CONFIG_FTPPUT]),
 OR(NVAR[CONFIG_FEATURE_MAKEDEVS_TABLE], NVAR[CONFIG_FEATURE_MAKEDEVS_LEAF]),
 OR(NVAR[CONFIG_FEATURE_MDEV_CONF], VAR[CONFIG_MDEV]),
 OR(VAR[CONFIG_TEST], NVAR[CONFIG_ASH_BUILTIN_TEST]),
 OR(NVAR[CONFIG_FEATURE_WTMP], VAR[CONFIG_FEATURE_UTMP], NVAR[CONFIG_LOGIN]),
 OR(NVAR[CONFIG_FEATURE_FBSET_FANCY], VAR[CONFIG_FBSET]),
 OR(NVAR[CONFIG_FEATURE_DEB_TAR_BZ2], VAR[CONFIG_DPKG_DEB], VAR[CONFIG_DPKG]),
 OR(VAR[CONFIG_FEATURE_BUFFERS_GO_ON_STACK], VAR[CONFIG_FEATURE_BUFFERS_GO_IN_BSS], NVAR[CONFIG_NITPICK], VAR[CONFIG_FEATURE_BUFFERS_USE_MALLOC]),
 OR(NVAR[CONFIG_FEATURE_LS_FILETYPES], VAR[CONFIG_LS]),
 OR(VAR[CONFIG_ASH], NVAR[CONFIG_FEATURE_EDITING_SAVEHISTORY]),
 OR(NVAR[CONFIG_FEATURE_IP_RULE], VAR[CONFIG_IP]),
 OR(NVAR[CONFIG_FEATURE_START_STOP_DAEMON_LONG_OPTIONS], VAR[CONFIG_GETOPT_LONG]),
 OR(NVAR[CONFIG_HUSH], VAR[CONFIG_FALSE]),
 OR(NVAR[CONFIG_FEATURE_TELNET_AUTOLOGIN], VAR[CONFIG_TELNET]),
 OR(NVAR[CONFIG_LOGREAD], VAR[CONFIG_FEATURE_IPC_SYSLOG]),
 OR(NVAR[CONFIG_FEATURE_TAR_LZMA], VAR[CONFIG_TAR]),
 OR(VAR[CONFIG_IFCONFIG], NVAR[CONFIG_FEATURE_IFCONFIG_STATUS]),
 OR(VAR[CONFIG_IFCONFIG], NVAR[CONFIG_FEATURE_IFUPDOWN_IFCONFIG_BUILTIN]),
 OR(NVAR[CONFIG_FEATURE_EDITING_SAVEHISTORY], VAR[CONFIG_FEATURE_EDITING]),
 OR(NVAR[CONFIG_FEATURE_WTMP], VAR[CONFIG_FEATURE_UTMP]),
 OR(VAR[CONFIG_IP], NVAR[CONFIG_FEATURE_IP_ADDRESS], VAR[CONFIG_FEATURE_IFUPDOWN_IP_BUILTIN]),
 OR(NVAR[CONFIG_FEATURE_IP_TUNNEL], VAR[CONFIG_IP]),
 OR(NVAR[CONFIG_FEATURE_TR_EQUIV], VAR[CONFIG_TR]),
 OR(VAR[CONFIG_IFUPDOWN], NVAR[CONFIG_FEATURE_IFUPDOWN_IFCONFIG_BUILTIN], NVAR[CONFIG_FEATURE_IFUPDOWN_IP]),
 OR(VAR[CONFIG_FEATURE_IPC_SYSLOG_BUFFER_SIZE], NVAR[CONFIG_FEATURE_IPC_SYSLOG]),
 OR(VAR[CONFIG_ASH], NVAR[CONFIG_ASH_READ_NCHARS]),
 OR(NVAR[CONFIG_DEVFSD_FG_NP], VAR[CONFIG_DEVFSD]),
 OR(NVAR[CONFIG_FEATURE_ROTATE_LOGFILE], VAR[CONFIG_SYSLOGD]),
 OR(NVAR[CONFIG_FEATURE_MOUNT_FLAGS], VAR[CONFIG_MOUNT]),
 OR(VAR[CONFIG_DIFF], NVAR[CONFIG_FEATURE_DIFF_DIR]),
 OR(NVAR[CONFIG_FEATURE_INETD_SUPPORT_BUILTIN_ECHO], VAR[CONFIG_INETD]),
 OR(NVAR[CONFIG_FEATURE_IPC_SYSLOG_BUFFER_SIZE], VAR[CONFIG_FEATURE_IPC_SYSLOG]),
 OR(VAR[CONFIG_IFUPDOWN], NVAR[CONFIG_FEATURE_IFUPDOWN_IP]),
 OR(NVAR[CONFIG_MODPROBE], VAR[CONFIG_FEATURE_MODPROBE_MULTIPLE_OPTIONS], VAR[CONFIG_NITPICK]),
 OR(VAR[CONFIG_FEATURE_SYSLOG], NVAR[CONFIG_SU]),
 OR(NVAR[CONFIG_FEATURE_SETCONSOLE_LONG_OPTIONS], NVAR[CONFIG_GETOPT_LONG]),
 OR(NVAR[CONFIG_FEATURE_UNARCHIVE_TAPE], VAR[CONFIG_TAR], VAR[CONFIG_CPIO]),
 OR(VAR[CONFIG_FBSET], NVAR[CONFIG_FEATURE_FBSET_READMODE]),
 OR(VAR[CONFIG_IFCONFIG], NVAR[CONFIG_FEATURE_IFCONFIG_HW]),
 OR(VAR[CONFIG_START_STOP_DAEMON], NVAR[CONFIG_FEATURE_START_STOP_DAEMON_FANCY]),
 OR(NVAR[CONFIG_LASH], VAR[CONFIG_FALSE]),
 OR(NVAR[CONFIG_FEATURE_SH_IS_ASH], NVAR[CONFIG_FEATURE_SH_IS_HUSH]),
 OR(VAR[CONFIG_LS], NVAR[CONFIG_FEATURE_LS_USERNAME]),
 OR(NVAR[CONFIG_FEATURE_HDPARM_GET_IDENTITY], VAR[CONFIG_HDPARM]),
 OR(VAR[CONFIG_FEATURE_IP_ROUTE], NVAR[CONFIG_FEATURE_IFUPDOWN_IP_BUILTIN]),
 OR(NVAR[CONFIG_FEATURE_SH_IS_ASH], NVAR[CONFIG_FEATURE_SH_IS_MSH]),
 OR(VAR[CONFIG_IPCALC], NVAR[CONFIG_FEATURE_IPCALC_LONG_OPTIONS]),
 OR(VAR[CONFIG_IPCALC], NVAR[CONFIG_FEATURE_IPCALC_FANCY]),
 OR(VAR[CONFIG_FIND], NVAR[CONFIG_FEATURE_FIND_MMIN]),
 OR(VAR[CONFIG_RMMOD], VAR[CONFIG_INSMOD], VAR[CONFIG_MODPROBE], NVAR[CONFIG_FEATURE_2_4_MODULES]),
 OR(VAR[CONFIG_DEVFSD], NVAR[CONFIG_DEVFSD_VERBOSE]),
 OR(NVAR[CONFIG_FEATURE_FIND_MTIME], VAR[CONFIG_FIND]),
 OR(NVAR[CONFIG_FEATURE_UDHCP_DEBUG], VAR[CONFIG_APP_UDHCPC], VAR[CONFIG_APP_UDHCPD]),
 OR(NVAR[CONFIG_FEATURE_TFTP_PUT], VAR[CONFIG_TFTP]),
 OR(VAR[CONFIG_HTTPD], NVAR[CONFIG_FEATURE_HTTPD_SETUID]),
 OR(VAR[CONFIG_FEATURE_UTMP], NVAR[CONFIG_WHO], NVAR[CONFIG_GETTY]),
 OR(NVAR[CONFIG_IFUPDOWN], VAR[CONFIG_RUN_PARTS]),
 OR(VAR[CONFIG_NITPICK], NVAR[CONFIG_FEATURE_BUFFERS_USE_MALLOC]),
 OR(NVAR[CONFIG_FEATURE_SH_IS_HUSH], NVAR[CONFIG_FEATURE_SH_IS_MSH]),
 OR(VAR[CONFIG_INIT], NVAR[CONFIG_FEATURE_INITRD]),
 OR(VAR[CONFIG_LESS], NVAR[CONFIG_FEATURE_LESS_REGEXP]),
 OR(VAR[CONFIG_WGET], NVAR[CONFIG_FEATURE_WGET_AUTHENTICATION]),
 OR(NVAR[CONFIG_FEATURE_XARGS_SUPPORT_QUOTES], VAR[CONFIG_XARGS]),
 OR(VAR[CONFIG_FEATURE_IP_ROUTE], NVAR[CONFIG_IPROUTE]),
 OR(NVAR[CONFIG_FEATURE_MINIX2], VAR[CONFIG_FSCK_MINIX], VAR[CONFIG_MKFS_MINIX]),
 OR(NVAR[CONFIG_FEATURE_LS_COLOR], VAR[CONFIG_GETOPT_LONG]),
 OR(NVAR[CONFIG_FEATURE_SH_IS_LASH], NVAR[CONFIG_FEATURE_SH_IS_NONE]),
 OR(VAR[CONFIG_FEATURE_2_4_MODULES], NVAR[CONFIG_FEATURE_INSMOD_VERSION_CHECKING]),
 OR(VAR[CONFIG_IFCONFIG], NVAR[CONFIG_FEATURE_IFCONFIG_BROADCAST_PLUS]),
 OR(NVAR[CONFIG_IPCS], VAR[CONFIG_FEATURE_SUID]),
 OR(NVAR[CONFIG_FEATURE_DATE_ISOFMT], VAR[CONFIG_DATE]),
 OR(VAR[CONFIG_INSTALL_APPLET_DONT], VAR[CONFIG_INSTALL_APPLET_HARDLINKS], VAR[CONFIG_INSTALL_APPLET_SYMLINKS]),
 OR(NVAR[CONFIG_FEATURE_VI_OPTIMIZE_CURSOR], VAR[CONFIG_VI]),
 OR(VAR[CONFIG_MV], NVAR[CONFIG_FEATURE_MV_LONG_OPTIONS]),
 OR(VAR[CONFIG_ASH], NVAR[CONFIG_ASH_BUILTIN_ECHO]),
 OR(VAR[CONFIG_ASH], NVAR[CONFIG_ASH_ALIAS]),
 OR(VAR[CONFIG_LASH], NVAR[CONFIG_FEATURE_SH_IS_LASH]),

## Simplify the data for later analysis

In [15]:
from _utils import parse_solution_overview

data_initial = parse_solution_overview(INPUT_SAMPLE_ARCHIVE)
data_initial = data_initial.drop_duplicates(
    subset=["Instance", "AlgorithmID", "AlgorithmIteration", "ModelID", "Settings"]
)
data_initial.loc[data_initial["Path"].isna(), "SampleSize"] = None
data_initial = data_initial[
    [
        "Instance",
        "#Variables",
        "#Clauses",
        "Algorithm",
        "Settings",
        "Time(s)",
        "SampleSize",
        "Path",
    ]
]
data_initial.rename(
    columns={
        "Time(s)": "runtime",
        "#Variables": "num_vars",
        "#Clauses": "num_clauses",
        "Instance": "instance_name",
        "Path": "path_to_baseline_sample",
        "Algorithm": "baseline_alg",
        "Settings": "baseline_alg_conf",
        "SampleSize": "sample_size",
    },
    inplace=True,
)
data_initial.to_json("./00_simple_baseline_data.json.zip")
data_initial

Found the data folders: {'2024-02-23_21-52-36/', '2024-02-23_21-52-29/', '2024-02-20_15-34-55/', '2024-02-20_15-35-55/', '2024-02-23_21-52-42/', '2024-02-23_21-52-24/'}
Deleting YASA entries
Deleting YASA entries
Deleting YASA entries
Deleting YASA entries
Deleting YASA entries
Deleting YASA entries

,instance_name,num_vars,num_clauses,baseline_alg,baseline_alg_conf,runtime,sample_size,path_to_baseline_sample
0,aaed2000,1298,3036,FIDE-ICPL,t2,62.188,96.0,2024-02-23_21-52-36/1_1_0_1_sample.csv
1,aaed2000,1298,3036,FIDE-Chvatal,t2,900.003,NaN,None
2,aaed2000,1298,3036,Incling,t2,48.432,161.0,2024-02-23_21-52-36/1_1_2_1_sample.csv
3,aaed2000,1298,3036,FIDE-YASA,t2_m1_null,4.939,102.0,2024-02-23_21-52-36/1_1_3_1_sample.csv
4,aaed2000,1298,3036,FIDE-YASA,t2_m3_null,10.284,94.0,2024-02-23_21-52-36/1_1_4_1_sample.csv
...,...,...,...,...,...,...,...,...
2536,atlas_mips32_4kc,1229,2875,FIDE-YASA,t2_m10_null,23.335,66.0,2024-02-23_21-52-24/9_1_6_1_sample.csv
2537,atlas_mips32_4kc,1229,2875,ACTS-IPOG-FT,t2,900.002,NaN,None
2538,atlas_mips32_4kc,1229,2875,ACTS-IPOG-CSP,t2,900.009,NaN,None
2539,atlas_mips32_4kc,1229,2875,ACTS-IPOF-FT,t2,900.009,NaN,None
2540,atlas_mips32_4kc,1229,2875,ACTS-IPOF-CSP,t2,900.035,NaN,None